language: rust

rust:
    - "nightly"
    - "beta"
    - "stable"
    - "1.3.0"

os:
    - linux

matrix:
  allow_failures:
    - rust: "1.3.0"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libgtk-3-dev

sudo: false

cache:
  directories:
    - $HOME/.ccache

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=/usr/lib/ccache:$HOME/.local/bin:/Users/travis/Library/Python/2.7/bin:$PATH

script:
    - rustc --version
    - cargo --version
    - travis-cargo build
    - travis-cargo test
    - travis-cargo --only nightly bench
    - travis-cargo --only stable doc

after_success:
    - if [ ${TRAVIS_OS_NAME} != "osx" ]; then travis-cargo coveralls --no-sudo; fi
    - type ccache >/dev/null 2>&1 && ccache -s

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
